### ISSUE TITLE
betterlockscreen fails when waking from suspend.

### ISSUE THREAD

**Issue by ljfoster97** [archcraft-os/archcraft#113]
When laptop is locked and suspended/sleep, I cannot wake the device by pressing keys. Instead, I have to press the power button. It takes about 5 seconds to actually wake up and then betterlockscreen shows "locking..." and then "locking failed!" even though the screen is already locked. The lock screen then flashes white and resets before letting me enter my password to login.

**Comment by ZeusThundr** [comment]
try adding apci=force to kernel parameters and updating grub you could also try using the ignore apci kernel parameter
`sudo vim /etc/default/grub`
go to grub cmdline inside the parenthesis
`sudo update-grub`
I hear this is common bc the apci std on a lot mobo is implemented wrong due to windows having it configured differently than the standard. Hope this helps.

**Comment by paarthjuneja** [comment]
Open the application called "Power Manager". Then go to "System". Change "When laptop lid is closed" to "Suspend". Now press "Plugged in" and again do the previous step.
