### ISSUE TITLE
Stuck in first loading screen when booting from USB (the first screen with the logo and the loading bar)

### ISSUE THREAD

**Issue by alexburgh** [archcraft-os/archcraft#150]
The loading bar fills up and then nothing happens (the OS doesn't boot up). 

My laptop model: Huawei Matebook 14
CPU: AMD Ryzen 4600H with integrated AMD graphics, so no Nvidia issues.

**Comment by adi1090x** [comment]
Have you tried booting with 'CopytoRAM' mode?

**Comment by alexburgh** [comment]
> Have you tried booting with 'CopytoRAM' mode?

Yes, same problem, unfortunately

**Comment by adi1090x** [comment]
Create a bootable USB correctly, Here : https://archcraft.io/blog/usb.html

**Comment by adi1090x** [comment]
Also, Press `ESC` key on plymouth to see the boot logs.

**Comment by VaibhavAcharya** [comment]
Same thing occurred with me when I flashed the drive with Rufus. I recommend using Etcher for flashing the ISO. Worked smoothly after it.

**Comment by clevrf0x** [comment]
Same issue here, but it will fix if i change usb partition scheme to MBR, but HDD is running on GPT scheme
is there a fix ?

**Comment by rlad78** [comment]
> Same thing occurred with me when I flashed the drive with Rufus. I recommend using Etcher for flashing the ISO. Worked smoothly after it.

Same here. Not entirely sure what BalenaEtcher does differently than Rufus, but I had the same issue with the ArcoLinux installer as well. Happens on both MBR and GPT partition schemes created by Rufus. 

The issue is that the installer can't find the USB drive again during boot. Saw something like `Waiting 10sec for /dev/disk/device-by-id/[my-usb-drive-name]...`

Not sure if this is an Archcraft-specific issue.
