### ISSUE TITLE
Wifi connection not working

### ISSUE THREAD

**Issue by leathium** [archcraft-os/archcraft#160]
hello,

i have connected my computer to my wifi network and started the archcraft installer but it says i am not connected to the internet so i tested in on the browser wich also says im not connected to the internet. 
i can also see that my wifi connection frequently disconnects. i know this is not an issue with my wifi dongle because i have tested it on Arch, manjaro, pop_os and more

![20210626_151656](https://user-images.githubusercontent.com/41258148/123514139-a1e9fb00-d691-11eb-8df2-608f9f2d6088.jpg)

**Comment by izedamo** [comment]
We would need to know your wifi card details. You can do `lspci | grep Network`. Depending on that, it may require installing additional wifi drivers - open source or proprietary. Apart from this, iwd and wpa_supplicant both come installed by default in the distro and that used to create problems for me with frequent disconnections as my driver was buggy with background scans. So I removed iwd and tried that. No more disconnections :) Seems by default wpa_supplicant is not performing bg scan.

**Comment by verajosemanuel** [comment]
same here. Wifi worked at boot and suddenly disconnects randomly.
Solved this way:

```
sudo systemctl stop iwd
sudo systemctl disable iwd
```

and reboot

**Comment by ALDRICHCODE45** [comment]
1

**Comment by All3yp** [comment]
I'm also having the same problem and I can't find a solution anywhere :( 

Btw This is an old MacAir that doesn't support updates and has very little ROM memory.

![image](https://github.com/archcraft-os/archcraft/assets/29764688/95bb0a9d-13fd-47da-9092-becbc8817d2a)

**Comment by All3yp** [comment]
I ran a dmesg and this was the output. it seems there’s an error loading the driver because it’s not supported, but then a supported driver has loaded successfully (?) I am not sure I understand. I feel like this is something important.

Also I tried running wpa_supplicant with a minimal wpa_supplicant.conf, this was the output (with error)
![image](https://github.com/archcraft-os/archcraft/assets/29764688/f9fdb9d9-9f41-415d-a048-1c2244c7635e)
![image](https://github.com/archcraft-os/archcraft/assets/29764688/ccc7f99a-6295-4d9d-9a76-4bf4a3c8be2c)
