### ISSUE TITLE
Archcraft - freezing after coming out of suspend

### ISSUE THREAD

**Issue by DetectiveCatt** [archcraft-os/archcraft#176]
Why is the suspend option not working? Once I suspend the laptop, and turn it back on, I see a wallpaper kind of thing with "enter password to enter" (something along those lines) on the bottom left. Pressing keys doesn't help, I entered the password and pressed return (mind that the screen was stuck, I couldn't see the things I was typing), it was still stuck and the only option I had was to hold the power button and force shut it down... am I the only one experiencing it?

**Comment by middieNomad** [comment]
@DetectiveCatt , I am on the same boat as you!!

Archcraft uses `betterlockscreen`, which inturn uses `i3lock`. The only way I could recover my x11 session  this was by killing the `i3lock` processes. I have juicessh installed on my phone, I ssh into the archcraft box, and kill the damn i3lock process. I changed the power management settings so that archcraft does not suspend anymore.

**Comment by DetectiveCatt** [comment]
Oh haha, it was a hassle for me to figure out and after like a week I switched to endeavour and then to mint. I just want a distro that doesn't need much maintenance because I don't have much time xd

Also is your phone android? or iOS? or wut

**Comment by middieNomad** [comment]
Nvm. I use android, btw..
