### ISSUE TITLE
Feature request: downloadable TAR file for WSL install

### ISSUE THREAD

**Issue by verajosemanuel** [archcraft-os/archcraft#183]
I like Archcraft a lot, and i would like to install it as my main WSL distribution at work. (I have it as my main personal laptop OS already)
I use WSLg version from development insider channel so I can use bspwm or any other tiling window manager with no issue.
Seems that the only way to do it is downloading as TAR file and force installation using this procedure (works for any other linux distribution):

https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro

Thanks

**Comment by ThatOneCalculator** [comment]
Since WSL is CLI based, just use Arch.

**Comment by verajosemanuel** [comment]
Please read again. I use WSLg
It’s not cli based but GUI based.

**Comment by SnippetsTeam** [comment]
other option is using EasyWSL
https://github.com/redcode-labs/easyWSL

but we need a docker image. Both options not available

**Comment by adi1090x** [comment]
Too Much Work! Maybe in future.

**Comment by JuanIPlanes** [comment]
### Hi.
I have a old hardware, and I can't run archcraft, installed in the disk. BUT,
lately, i'm using WSL(2) with Arch Linux, and run perfectly.
I try to install archcraft in the WSL, and i didn't succeed, because i didn't get the **.tar** from your repos.
please, can you guys make a .tar from your ISO image, or simil?

I read the following articles, hope this is helpful.


### [easyWSL](https://github.com/redcode-labs/easyWSL)
_Create WSL distros based on Docker Images._
### [WSL install another distro](https://gist.github.com/artman41/858450e2c29b239d8692213b684ada25) (artman41)
_Instructions on how to install a custom distro in WSL2 (Windows SubSystem for Linux 2)_
### [WSL Distro Launcher](https://github.com/Microsoft/WSL-DistroLauncher)
_C++ reference implementation for a Windows Subsystem for Linux (WSL) distribution installer/launcher application._
