### ISSUE TITLE
Only one resolution available

### ISSUE THREAD

**Issue by demondave** [archcraft-os/archcraft#202]
Version: **Archcraft 2021.10**

When selecting the resolution in the context menu or in xrandr, there is only one resolution available.

Temporary fix (resets if you restart): 

Generate the modeline for the resolution you want:
`cvt 1600 900 60`

Result:
`# 1600x900 59.95 Hz (CVT 1.44M9) hsync: 55.99 kHz; pclk: 118.25 MHz
Modeline "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync`

Add a new mode with the desired resolution:
`xrandr --newmode "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync`

Add the new mode to the display adapter (eDP1 is my adapter):
`xrandr --addmode eDP1 1600x900_60.00`

Set the resolution on the desired display adapter (or use the context menu):
`xrandr --output eDP1 --mode 1600x900_60.00`

**Comment by ByteDream** [comment]
It looks like this is a knowing issue on linux in general and caused by buggy hardware or drivers, as mentioned by the [arch wiki](https://wiki.archlinux.org/title/Xrandr#Adding_undetected_resolutions) and has to be "fixed" with the temporary fix provided here or in the wiki (just place it in `.config/openbox/autostart` or `.config/bspwm/bspwmrc`, depending on your wm)
