### ISSUE TITLE
Cant boot to Arch

### ISSUE THREAD

**Issue by sandeepdokala** [archcraft-os/archcraft#238]
So, I am done with windows 11, and tried to install windows 10. during installation of windows 10, i accidentally deleted the system partition. now i cant boot into the archcraft. i looked up into my efi folder and i cant find my archcraft boot folder. please help me recover my arch system.

**Comment by AbhayF8** [comment]
If u have accidently deleted the efi partition and not the archcraft linux root partition then u just need to boot live archcraft iso and chroot into the root of archcraft linux partition and just do `sudo grub-install /dev/sdXY` where XY is the efi partition.

**Comment by Suleman-Elahi** [comment]
Can you please clarify how to do this. I am too frustrated right now. I am tried of googling. I don't know how to chroot into the partition.

I have reinstalled it like a 10 times since last night and it never installs Grub. I am dual booting it and I have Windows 10 alongside.

From the live ISO, I did this:

```
   ~ sudo grub-mkconfig -o /boot/grub/grub.cfg
/usr/bin/grub-probe: error: failed to get canonical path of `airootfs'.
   ~ 
```

   ~ sudo os-prober
/dev/sda1@/efi/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi
   ~ sudo update-grub
/usr/bin/grub-probe: error: failed to get canonical path of `airootfs'.
   ~ 

Nothing seems to be working.
