### ISSUE TITLE
'Out of Memory' issue when booting into ISO

### ISSUE THREAD

**Issue by missioncontrolceo** [archcraft-os/archcraft#342]
Using the latest ISO burned to a USB stick, when trying to boot into Archcraft to initiate an install you get frozen on a black screen that simply says 'error out of memory, press any key to continue...' Only pressing any key does nothing and I have to restart the computer. There just doesn't seem any way to boot into this ISO. Have tried burning this USB via Popsicle, Ventoy and Etcher. All same problem. Looking this up - this seems to be a grub issue of some sort. 

Would absolutely LOVE to try Archcraft but cannot get past this issue.

**Comment by ViniciusRed** [comment]
How much space does the pendrive have and what are the specifications of the machine you are installing?

**Comment by ViniciusRed** [comment]
I started using linux because my pc and notebook have 3 to 4 ram and because it is a dual core processor in the notebook the bios is locked by the manufacturer gave safe boot problem but can use safe boot normally fixing after installation and on my pc because the video card is old and the nvidia driver not have more update for recent linux the notebook is UEFI in the bios to change to legacy but is locked by the manufacturer my pc is lagacy and distro (notebook and pc) worked normally on the pc had a problem because of the video card driver changing to onboard the distro works normally (notebook year: 2018 PC: 2004)

**Comment by ashroyxi** [comment]
Same issue here, i used that pendrive for installing win11/10, garuda/arch/ubuntu now only archcraft not working.

**Comment by adi1090x** [comment]
Few people have this issue in past, but it was solved.
