### ISSUE TITLE
Shutdown, Lockout etc is not working

### ISSUE THREAD

**Issue by M-Imtiaz** [archcraft-os/archcraft#35]
I have a hp pavilion core i5 laptop with nvidia card. When I click on shutdown, Restart, Lockout etc using menu, the system just freeze and didn't do anything. I had to forcefully shutdown by pressing the power button. I don't know what's the issue. If you need any kind of logs etc I will provide here. I am using a terminal for now to shutdown, restart, etc.

The next issue is when I lockout using shortcut, then entering the password again is not working. just froze on the lock screen. 

P.S I installed Gnome and everything work fine. I guess the mention issues lie with just openbox

**Comment by CA1R7** [comment]
@M-Imtiaz  
+ try run `sudo grub-update`.
if it still does not working.
 - `sudo vi /etc/default/grub`
change `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"` to `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi=force"` Save and exit using.
Finally run,
`sudo update-grub`

**Comment by thonkdifferent** [comment]
I had the same issue. It seems that the power menu applet is completely broken. More exactly the confirmation prompt is broken because it hangs the system. A workaround that is to disable the confirmation prompt.

Workaround instalation steps:

1. Download [powermenu_workaround.zip](https://github.com/archcraft-os/archcraft/files/5174779/powermenu_workaround.zip) and unzip it
2. backup the current powermenu applet: 
`$ cp ~/.config/rofi/bin/powermenu ~/.config/rofi/bin/powermenu_backup`
3. install the workaround:
`$ cp /path/to/powermenu_workaround ~/.config/rofi/bin/powermenu`(reply yes to any prompts regarding file overriding if required)
4. Enjoy

To revert back to the original state, run:
`$ cp ~/.config/rofi/bin/powermenu_backup ~/.config/rofi/bin/powermenu`

Hope that helps!

**Comment by adi1090x** [comment]
is it resolved?

**Comment by M-Imtiaz** [comment]
@adi1090x Sorry I didn't try the solutions given here as I moved to Arch. I waited 2 days for replies then I moved to Arch. Will definitely try out in the near future

**Comment by ignaciops** [comment]
> is it resolved?

@adi1090x using the solution posted by @thonkdifferent fixes the powermenu issue. 

The issue with lockout shortcut not affected me. Not sure if the powermenu fix solves the lockout one too.

**Comment by nexty5870** [comment]
having the same issue, the workaround work but trigger my OCD as it's not align with the thematic, any chance we can have this fix?

**Comment by ignaciops** [comment]
I'm not using arch craft anymore, but you can do this.
Right click on the desktop.
Look for openbox options.
There should be an option that says something like reconfigure or rebuild.
Select it. 

Next time you shut down or logout it will keep the original menu style but it will have the fix applied. At least it worked for me that way.

**Comment by rendekarf** [comment]
Hi, I'm having the same issue. When I go to Restart or Shutdown I get a confirmation dialog that presents the options `yes / no / y / n` but nothing happens when I click any one of them. The dialog disappears when I hit return.

When I right click the desktop to do the same I get a different dialog with a prompt where it works when I type in `yes`. Not sure what the issue is tbh.

None of the above solutions worked for me.

**Comment by darksecureproof** [comment]
Its very simple in the powermeny select the option like logout, reboot, etc and insted of click press ENTER, then a popup window will give you the option to insert yes/y then press enter again and thats it

**Comment by antoine-hnkx** [comment]
> Hi, I'm having the same issue. When I go to Restart or Shutdown I get a confirmation dialog that presents the options `yes / no / y / n` but nothing happens when I click any one of them. The dialog disappears when I hit return.
> 
> When I right click the desktop to do the same I get a different dialog with a prompt where it works when I type in `yes`. Not sure what the issue is tbh.
> 
> None of the above solutions worked for me.
> 
> **UPDATE**: I've been playing around with the shell script at `$HOME/.config/rofi/bin/powermenu` and it looks like for some reason the dialog brought up by `ans=$(rdialog &)` is instantly disappearing without accepting any input. That's why the next prompt which includes possible options for the initial dialog is shown.
> 
> No idea why this is happening, any help would be appreciated.

You can add `me-accept-entry: "!MousePrimary";` to your rofi config, I proposed a fix [here](https://github.com/archcraft-os/archcraft-skeleton/pull/1) but it was rejected, hope this helps!

**Comment by hajsf** [comment]
I just installed Archcraft and got the same issue
