### ISSUE TITLE
appimage does not work in "places"

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#359]
appimage doesn't work when:
Openbox > right mouse click > Places > Applications > click on BalenaEtcher-1.14.3-x64.Appimage
(opens archives application)

appimage works when:
Openbox > Thunar > user > Applications > click on BalenaEtcher-1.14.3-x64.Appimage

**Comment by ab0veall** [comment]
seems like you're experiencing an issue with running an AppImage file using Openbox. Specifically, when you right-click on the desktop, go to "Places," navigate to "Applications," and click on the BalenaEtcher-1.14.3-x64.Appimage file, it opens the archive application instead of executing the AppImage.

To address this, let's explore some possible solutions. It appears that the issue lies in the default action associated with the AppImage file type within Openbox. When you access the file through Thunar (the file manager), it executes the AppImage as expected. This suggests that the problem may be related to the desktop environment's configuration.

One potential solution is to modify the Openbox configuration to associate the correct action with the AppImage file type. To do this, you can edit the Openbox menu configuration file and specify the appropriate command to execute the AppImage when clicked from the "Places" menu. You may need to consult the Openbox documentation or seek guidance from the Openbox community to ensure the correct configuration changes are made.

Alternatively, you can try a workaround by creating a desktop entry for the BalenaEtcher AppImage manually. This involves creating a .desktop file in the ~/.local/share/applications directory or /usr/share/applications directory. The .desktop file should contain the necessary information to launch the AppImage when clicked. You can find examples and further guidance on creating .desktop files in the freedesktop.org Desktop Entry Specification.

Remember, it's essential to make any modifications or additions to your system configuration with caution and create backups as a precautionary measure. If you're uncomfortable making these changes yourself, consider seeking assistance from experienced Openbox users or the Openbox community to ensure the changes are made correctly.

I hope these suggestions help you resolve the issue and allow you to run the BalenaEtcher AppImage seamlessly within Openbox. If you have any further questions or need additional assistance, feel free to ask. Good luck!

**Comment by adi1090x** [comment]
Always use a `.desktop` file for you app-images. that way you can access them using both, openbox menu and rofi launcher.
