### ISSUE TITLE
Screen lock not working on lid close

### ISSUE THREAD

**Issue by seeval** [archcraft-os/archcraft#370]
Screen lock not working on lid close on laptop, system fully updated. 

Please see screenshot, see notification upon opening lid again.

![Screenshot_2023-05-24-13-24-10_1920x1080](https://github.com/archcraft-os/archcraft/assets/34445198/f5379c3f-d2c6-44db-9158-9e3a473fa9eb)

**Comment by ab0veall** [comment]
appears that you're experiencing an issue where the screen lock feature is not working properly when you close the lid of your laptop, even though your system is fully updated. To troubleshoot this problem, you can try the following steps:

Verify Power Settings: Make sure that your power settings are correctly configured to lock the screen when the lid is closed. You can usually find these settings in the power management or screen settings section of your system preferences. Check if the option to lock the screen on lid close is enabled.

Update Screen Lock Tools: Check if there are any updates available for the screen lock tools installed on your system. You can use your package manager or software update tool to check for updates and install them if there are any. After updating, restart your system and see if the issue is resolved.

Try Different Screen Lock Tools: If updating the screen lock tools doesn't fix the problem, you can try using a different screen lock tool. There are various options available, such as GNOME Screensaver, xscreensaver, or light-locker. Install an alternative screen lock tool using your package manager, set it as the default screen lock tool, and test if it works when you close the lid.

Check System Logs: It's worth checking the system logs for any error messages or clues related to the screen lock issue. The system logs can often provide helpful information about what might be causing the problem. You can typically find the system logs in the /var/log directory. Look for log files related to screen lock tools or power management and examine them for any relevant error messages.

Seek Community Support: If the problem persists, consider seeking help from the Linux community. You can visit forums or online communities specific to your Linux distribution or desktop environment. Provide details about your system, the troubleshooting steps you've already taken, and the exact error message you're encountering. Experienced users and developers in the community may be able to offer additional insights or guidance to help resolve the issue.

**Comment by lolmokha** [comment]
Ever since I installed the OS on my new laptop I'm having the same issue.  The power settings are configured to lock the system on lid close.  Betterlockscreen is on Version 4.0.4.

**Comment by matinabbasi788** [comment]
i have same problem archcraft cant lock screen systemc but with crl alt L everything is okey

**Comment by jiangtao69039** [comment]
![image](https://github.com/archcraft-os/archcraft/assets/20572131/214f70cc-3b3d-40d2-ae9f-597d013a39a6)
how to fix this issue?

**Comment by lolmokha** [comment]
Found the fix on the Telegram channel:
- Create file `.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml`
- Add to file:
```
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-session" version="1.0">
  <property name="general" type="empty">
    <property name="LockCommand" type="string" value="betterlockscreen --lock"/>
  </property>
</channel>

```

**Comment by seeval** [comment]
> Found the fix on the Telegram channel:
> 
> * Create file `.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml`
> * Add to file:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <channel name="xfce4-session" version="1.0">
>   <property name="general" type="empty">
>     <property name="LockCommand" type="string" value="betterlockscreen --lock"/>
>   </property>
> </channel>
> ```

Seemed to fix for me, thank you

**Comment by seeval** [comment]
was having issues using betterlockscreen, for some reason would unlock and lock multiple times on wakeup. 

set xflock4 as lockcommand by running this command in term: 

xfconf-query -c xfce4-session -p /general/LockCommand -s "xflock4" --create

**Comment by adi1090x** [comment]
Here's the working fix:

- Create file `.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml`
- Add to file:
```
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-session" version="1.0">
  <property name="general" type="empty">
    <property name="LockCommand" type="string" value="xflock4"/>
  </property>
</channel>
```

- Edit `/usr/local/bin/xflock4` and put this command there : `betterlockscreen --lock &`
