### ISSUE TITLE
Super key for rofi stopped working

### ISSUE THREAD

**Issue by thiagosfsilva** [archcraft-os/archcraft#82]
Hello. First of all, thanks for the distro, really enjoying it so far. I was messing with my keyboard layouts trying to get international accents to work, and somehow I managed to mess up the use of the Super (Windows) key alone to bring up Rofi.

If I actually press Alt+F1 I can get it to come up, but if I press Super nothing happens. Super + other things still work as normal. Any suggestions on how to recover the initial behavior? For now I have changed it to A-space on rc.xml. Thank you!

**Comment by Thomashighbaugh** [comment]
its probably related to however he is binding additional keys to super. I do something similar in my AwesomeWM configuration and keep a line in my `.xprofile` for this purpose that is  
`run xcape -e 'Super_L=Super_L|Control_L|Escape' ` (run being a function within xprofile)

then in my awesomewm keybindings I have Super+Control+Escape launch rofi (will be different and within sxhkdrc for BSPWM and Openbox, neither of which I know well) 

Essentially it is saying more than just super to the system, but a combo of keys and may be more fickle in its use on BSPWM and Openbox (it is more fickle in qtile I can say for sure) but for my purposes xcape doesn't interfer with my other bindings and it 'just works' 

I am sure Adi is using some slightly different system, I was inspired by Manjaro's awesomewm default in coming up with my own, but I would think your issue lies in whatever that solution may have been. 

Hope that helps or gives you a starting place at least.  
- Tom

**Comment by gitbucket-crypto** [comment]
> Hello. First of all, thanks for the distro, really enjoying it so far. I was messing with my keyboard layouts trying to get international accents to work, and somehow I managed to mess up the use of the Super (Windows) key alone to bring up Rofi.
> 
> If I actually press Alt+F1 I can get it to come up, but if I press Super nothing happens. Super + other things still work as normal. Any suggestions on how to recover the initial behavior? For now I have changed it to A-space on rc.xml. Thank you!

I changed in rc.xml and put these for accept mouse click:

rofi -show drun -location 6 -me-select-entry '' -me-accept-entry 'MousePrimary'

**Comment by thiagosfsilva** [comment]
Thanks! I ended up installing another distro and WM in the mean time, so I'm marking the issue as closed for now. Will definitely be revisiting it in the near future.

**Comment by Thomashighbaugh** [comment]
Good stuff, if you have additional questions on that particular topic, feel free to raise an issue on my dotfiles and I will be happy to help and can even dive into random window managers if time permits. 

Exploring Manjaro's default configurations of various tiling window managers I found very helpful early on personally, but if you found something that works that's even better. Personally can't live without hitting super and bringing up the application launcher so I do get the frustration.
